on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: pipeline
    steps:
    - name: lint
      uses: egonbraun/python-ci-action@main
      with:
        disable_test: "true"
    - name: test
      uses: egonbraun/python-ci-action@main
      with:
        disable_lint: "true"
