on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Pipeline
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      uses: egonbraun/python-lint-action@main
    - name: Test
      uses: egonbraun/python-unittest-action@main
