on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Pipeline
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      uses: egonbraun/python-ci-action@main
      with:
        disable_test: "true"
    - name: Test
      uses: egonbraun/python-ci-action@main
      with:
        disable_lint: "true"
